name: couplers
description: "A love events diary."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.2
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  ming_cute_icons: ^0.0.7
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  supabase_flutter: ^2.8.3
  logger: ^2.5.0
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.4
  toastification: ^2.3.0
  image: ^4.3.0
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  image_gallery_saver_plus: ^3.0.5
  flutter_cache_manager: ^3.4.1
  http: ^1.3.0
  table_calendar: ^3.1.3
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.3
  permission_handler: ^11.3.1
  free_map: ^2.0.2
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  flutter_onboarding_slider: ^1.0.11
  device_info_plus: ^11.2.0
  webview_flutter: ^4.10.0
  smooth_page_indicator: ^1.2.0+3
  file_picker: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - config.json
    - assets/images/
    - assets/images/default_event_image.png
    - assets/images/default_user_image.png
    - assets/fonts/

  fonts:
    - family: CouplersIcons
      fonts:
        - asset: assets/fonts/CouplersIcons.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo_icon.png"
